image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.npm-lock
      npm install
      rm /tmp/.npm-lock
    command: npx cypress install
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
    command: npx cypress open
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
